repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.2
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.2
  hooks:
    - id: uv-lock
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.25.1
  hooks:
    - id: gitleaks


- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy --strict app tests
      language: system
      pass_filenames: false
      always_run: true

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest
      language: system
      pass_filenames: false
      always_run: true