repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      stages: [pre-commit]
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.2
  hooks:
    - id: uv-lock
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.25.1
  hooks:
    - id: gitleaks
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'
  hooks:
  -   id: mypy
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml", "-r", "."]

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest
      language: system
      pass_filenames: false
      always_run: true