{{- if .Values.payload.useConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "property24-bot.fullname" . }}-payload
  labels:
    {{- include "property24-bot.labels" . | nindent 4 }}
data:
  payload.json: |
{{- if .Values.payload.jsonContent }}
{{ .Values.payload.jsonContent | nindent 4 }}
{{- end }}
{{- end }}