# Example values for Property24 Bot with ntfy notifications
# Copy this file and customize it for your deployment:
#   helm install my-bot ./property24-bot -f my-values.yaml

# Notification Configuration (ntfy method)
notificationMethod: ntfy
ntfy:
  server: "https://ntfy.sh"
  topic: "your-unique-topic-name-here"  # REQUIRED: Change this!

# Application Configuration
app:
  pollInterval: 60
  locationName: "Stellenbosch"
  logLevel: "INFO"

# Image Configuration
# Update this after building and pushing your Docker image
image:
  repository: property24-bot  # Change to your registry/image
  tag: "0.1.0"
  pullPolicy: IfNotPresent

# Optional: Enable persistence for state database
persistence:
  enabled: false
  # enabled: true
  # size: 1Gi
  # storageClass: ""

# Optional: Set resource limits
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
