# Example values for Property24 Bot with ntfy notifications
# Copy this file and customize it for your deployment:
#   helm install my-bot ./property24-bot -f my-values.yaml

# Notification Configuration (ntfy method)
notificationMethod: ntfy
ntfy:
  server: "https://ntfy.sh"
  topic: "your-unique-topic-name-here"  # REQUIRED: Change this!

# Application Configuration
app:
  pollInterval: 60
  locationName: "Stellenbosch"
  logLevel: "INFO"

# Image Configuration
# Update this after building and pushing your Docker image
image:
  repository: property24-bot  # Change to your registry/image
  tag: "0.1.0"
  pullPolicy: IfNotPresent

# Optional: Enable persistence for state database
persistence:
  # enabled: false
  enabled: true
  size: 1Gi
  storageClass: ""

# Optional: Set resource limits
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Metrics Configuration
metrics:
  enabled: true
  port: 8000
  service:
    type: ClusterIP
    port: 8000
  # Enable ServiceMonitor if using Prometheus Operator
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    # labels:
    #   prometheus: kube-prometheus

# Volume mount for payload.json
payload:
  # If you want to use a ConfigMap for the payload
  useConfigMap: true
  configMapName: ""
  
  # If you want to mount from a PVC or hostPath
  usePersistentVolume: false
  persistentVolumeClaim: ""
  jsonContent: |
    {
      "bedrooms": 0,
      "bathrooms": 0,
      "availability": 0,
      "rentalRates": [],
      "sizeFrom": {
          "isCustom": false,
          "value": null
      },
      "sizeTo": {
          "isCustom": false,
          "value": null
      },
      "erfSizeFrom": {
          "isCustom": false,
          "value": null
      },
      "erfSizeTo": {
          "isCustom": false,
          "value": null
      },
      "floorSizeFrom": {
          "isCustom": false,
          "value": null
      },
      "floorSizeTo": {
          "isCustom": false,
          "value": null
      },
      "parkingType": 1,
      "parkingSpaces": 0,
      "hasFlatlet": null,
      "hasGarden": null,
      "hasPool": null,
      "furnishedStatus": 2,
      "isPetFriendly": null,
      "isRepossessed": null,
      "isRetirement": null,
      "isInSecurityEstate": null,
      "onAuction": null,
      "onShow": null,
      "propertyTypes": [
          4,
          5,
          6
      ],
      "autoCompleteItems": [
          {
              "id": 459,
              "name": "Stellenbosch",
              "parentId": null,
              "parentName": "Western Cape",
              "type": 2,
              "source": 0,
              "normalizedName": "stellenbosch"
          }
      ],
      "searchContextType": 1,
      "priceFrom": {
          "isCustom": false,
          "value": null
      },
      "priceTo": {
          "isCustom": false,
          "value": null
      },
      "searchType": 1,
      "sortOrder": 0,
      "developmentSubType": 0
    }